server:
  port: 8081
  contextPath: /message-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  zipkin:
    baseUrl: http://localhost:9411/
  sleuth:
    sampler:
      percentage: 1.0

# When enabled=false, traces log to the console. Comment to send to zipkin
sample:
  zipkin:
    enabled: true

# Note that we will use the JWT token to get user data
security:
  oauth2:
    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAk3++DS7Bqw6R8ICGBqAEyIVJj0Qu2UGeVAToIGncIZmFtxhVb9wgZzCcq+0EJIEz6gZEQpTTr4HoAfzk9ysnfug39MuIwPFsyseu0SMx9LAptueikOPabo8IswwhjAy4p1ers6SqgqKh/sI4UXT/vgph4sVwWEEiE2py9VBjP6gUG43CDKKMvVMmA0EzSYVxtakr5C1lTlu/Gl14zsSIaenSx+ANO3ZqOO27aMLg0009qbwGcWhqQAaX7cyR+QfP/Un+vwAzyZ3E/KfiUQSGaGEzclmQ+nPA9n8ArIv7iyj8MflroXj5JIdpalonXl3J+IR6J1o5MfCGI2oIDefnFwIDAQAB         
          -----END PUBLIC KEY-----
---
# user-webservice instance when used on Docker
spring:
  profiles: docker
  # Datasource and JPA configuration to be used for storing the OAuth authorization details
  # and token store
  datasource:
   url: jdbc:mysql://message-mysqldb:3306/message
   username: root
   password: password
   driver-class: com.mysql.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create
  zipkin:
    baseUrl: http://zipkinserver:9411/

eureka:
# Register our microservices to Eureka using hostnames in a Docker environment will not work, they will all get
# one and the same hostname. Instead we configure them to use its IP address during registration with Eureka.
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://eurekaregistry:8761/eureka/

# Define the port where the API gateway server would be running. This could always be port 8080
# since each docker container has it's own IP
server:
  port: 8080
  
africastalking:
# africas talking configs
  apiKey: 6507b4ce5177bfb968b87d954463f6da13345295f02dd4324b7caaebab25a7f7
  username: mastercard
  senderId: MCLFI
  shortCode: 40289
  sandboxUsername: sandbox
  sandboxShortCode: 67337
  sampleforwardUrl: http://localhost:8080/sandbox

spring.activemq.user: admin
spring.activemq.password: admin
spring.activemq.broker-url: tcp://activemq:61616?jms.redeliveryPolicy.maximumRedeliveries=5&jms.redeliveryPolicy.redeliveryDelay=30000&jms.redeliveryPolicy.initialRedeliveryDelay=30000