server:
  port: 8082
  contextPath: /task-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  zipkin:
    baseUrl: http://localhost:9411/
  sleuth:
    sampler:
      percentage: 1.0

# When enabled=false, traces log to the console. Comment to send to zipkin
sample:
  zipkin:
    enabled: true

# Note that we will use the JWT token to get user data
security:
  oauth2:
    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAk3++DS7Bqw6R8ICGBqAEyIVJj0Qu2UGeVAToIGncIZmFtxhVb9wgZzCcq+0EJIEz6gZEQpTTr4HoAfzk9ysnfug39MuIwPFsyseu0SMx9LAptueikOPabo8IswwhjAy4p1ers6SqgqKh/sI4UXT/vgph4sVwWEEiE2py9VBjP6gUG43CDKKMvVMmA0EzSYVxtakr5C1lTlu/Gl14zsSIaenSx+ANO3ZqOO27aMLg0009qbwGcWhqQAaX7cyR+QfP/Un+vwAzyZ3E/KfiUQSGaGEzclmQ+nPA9n8ArIv7iyj8MflroXj5JIdpalonXl3J+IR6J1o5MfCGI2oIDefnFwIDAQAB         
          -----END PUBLIC KEY-----
---
# task-webservice instance when used on Docker
spring:
  profiles: docker
  zipkin:
    baseUrl: http://zipkinserver:9411/

eureka:
# Register our microservices to Eureka using hostnames in a Docker environment will not work, they will all get
# one and the same hostname. Instead we configure them to use its IP address during registration with Eureka.
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://eurekaregistry:8761/eureka/

# Define the port where the API gateway server would be running. This could always be port 8080
# since each docker container has it's own IP
server:
  port: 8080
